services:
  zapadoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: zapadoo:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production